CREATE TABLE IF NOT EXISTS users (
	id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	telegram_id BIGINT NOT NULL UNIQUE,
	username VARCHAR(255) UNIQUE,
	name VARCHAR(255) 
);

CREATE INDEX IF NOT EXISTS idx_users_telegram_id ON users(telegram_id);