CREATE TABLE IF NOT EXISTS books (
	id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE, 
	book_name VARCHAR(255) NOT NULL UNIQUE,
	total_pages INT NOT NULL,
	current_pages INT NOT NULL
)

CREATE INDEX IF NOT EXISTS idx_books_user_id ON books(user_id);