CREATE TABLE IF NOT EXISTS trips (
	id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE, 

	from_station TEXT NOT NULL, 
	to_station TEXT NOT NULL,

	book_id BIGINT REFERENCES books(id) ON DELETE SET NULL, 

	departure_time TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_trips_user_id ON trips(user_id);